language: ruby
dist: trusty
rvm:
  - 2.2
install: gem install asciidoctor-pdf --pre

git:
  depth: 1
branches:
  only:
  - master
addons:
  apt:
    packages:
    - zsh

env:
  global:
  - ENCRYPTION_LABEL: "de1faff15945"
  - COMMIT_AUTHOR_EMAIL: "psprint@zdharma.org"

before_script:
- zsh --version
script:
- make
- make -C zsdoc pdf
- share/deploy_doc.sh
